# Generated by Django 2.2 on 2019-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='kwd',
            name='f_id',
        ),
        migrations.RemoveField(
            model_name='pkt',
            name='f_id',
        ),
        migrations.AlterField(
            model_name='file_name',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
